In [1]:
import datadotworld as dw
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = dw.load_dataset('dcereijo/player-scores', force_update=True)

In [2]:
print(dataset.dataframes)

{'appearances': LazyLoadedValue(<pandas.DataFrame>), 'club_games': LazyLoadedValue(<pandas.DataFrame>), 'clubs': LazyLoadedValue(<pandas.DataFrame>), 'competitions': LazyLoadedValue(<pandas.DataFrame>)}

In [3]:
df = dataset.dataframes["appearances"]

In [4]:
print(df.columns)

Index(['appearance_id', 'game_id', 'player_id', 'player_club_id',
       'player_current_club_id', 'date', 'player_name', 'competition_id',
       'yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played'],
      dtype='object')

In [5]:
df[df.player_name == "Cristiano Ronaldo"]

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
16458,2483945_8198,2483945,8198,418,985,2014-08-12,Cristiano Ronaldo,USC,0,0,2,0,90
19154,2481145_8198,2481145,8198,418,985,2014-08-19,Cristiano Ronaldo,SUC,0,0,0,0,45
19852,2481146_8198,2481146,8198,418,985,2014-08-22,Cristiano Ronaldo,SUC,1,0,0,0,45
22533,2475189_8198,2475189,8198,418,985,2014-08-25,Cristiano Ronaldo,ES1,0,0,1,0,90
27236,2475204_8198,2475204,8198,418,985,2014-09-13,Cristiano Ronaldo,ES1,0,0,1,0,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033384,3592218_8198,3592218,8198,985,985,2022-04-16,Cristiano Ronaldo,GB1,0,0,3,0,90
1036696,3592170_8198,3592170,8198,985,985,2022-04-23,Cristiano Ronaldo,GB1,1,0,1,0,90
1038856,3592202_8198,3592202,8198,985,985,2022-04-28,Cristiano Ronaldo,GB1,0,0,1,0,90
1041374,3592219_8198,3592219,8198,985,985,2022-05-02,Cristiano Ronaldo,GB1,0,0,1,0,90
1042271,3592187_8198,3592187,8198,985,985,2022-05-07,Cristiano Ronaldo,GB1,1,0,0,0,90

In [12]:
valuations = pd.read_csv('https://query.data.world/s/y4qg2twfvou4w2ghz6o3evju32g7yn?dws=00000')
players = pd.read_csv('https://query.data.world/s/gksm6hx4xzgjaed7tia2uzpafwvyjo?dws=00000')
players_stats = pd.read_csv('https://query.data.world/s/bl3zxtm4dujmo3yfctx6ec5t7digv6?dws=00000')

In [14]:
players_stats

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
0,158023,L. Messi,Lionel AndrÃ©s Messi Cuccittini,1987-06-24,31,170.18,72.1,"CF,RW,ST",Argentina,94,...,64+2,61+2,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2
1,190460,C. Eriksen,Christian Dannemann Eriksen,1992-02-14,27,154.94,76.2,"CAM,RM,CM",Denmark,88,...,71+3,71+3,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3
2,195864,P. Pogba,Paul Pogba,1993-03-15,25,190.50,83.9,"CM,CAM",France,88,...,76+3,77+3,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3
3,198219,L. Insigne,Lorenzo Insigne,1991-06-04,27,162.56,59.0,"LW,ST",Italy,88,...,63+3,58+3,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3
4,201024,K. Koulibaly,Kalidou Koulibaly,1991-06-20,27,187.96,88.9,CB,Senegal,88,...,73+3,77+3,77+3,77+3,73+3,76+3,85+3,85+3,85+3,76+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,204322,R. McKenzie,Rory McKenzie,1993-10-07,25,175.26,74.8,"RM,CAM,CM",Scotland,67,...,53+2,52+2,52+2,52+2,53+2,50+2,46+2,46+2,46+2,50+2
17950,239762,M. SipÄ¾ak,Michal SipÄ¾ak,1996-02-02,23,182.88,79.8,LB,Slovakia,59,...,57+2,55+2,55+2,55+2,57+2,57+2,58+2,58+2,58+2,57+2
17951,235155,J. Bekkema,Jan Bekkema,1996-04-09,22,185.42,89.8,GK,Netherlands,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17952,244883,A. Al Yami,Abdulrahman Al Yami,1997-06-19,21,175.26,64.9,"ST,LM",Saudi Arabia,59,...,41+2,35+2,35+2,35+2,41+2,39+2,32+2,32+2,32+2,39+2
17953,247187,JÃºnior Brumado,JosÃ© Francisco dos Santos JÃºnior,1999-05-15,19,190.50,79.8,ST,Brazil,59,...,41+2,40+2,40+2,40+2,41+2,40+2,40+2,40+2,40+2,40+2

In [8]:
players[(players.current_club_name.isna()) & (players.country_of_birth == "Argentina")]

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name
28,5890,Sergio,AlmirÃ³n,Sergio AlmirÃ³n,2013,1627,sergio-almiron,Argentina,Santa FÃ©,Argentina,...,right,180.0,NaN,11000000.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/sergio-almiron...,IT1,NaN
291,58383,Gonzalo,Castillejos,Gonzalo Castillejos,2017,441,gonzalo-castillejos,Argentina,Leones,Argentina,...,right,182.0,NaN,1500000.0,NaN,B2B Group,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/gonzalo-castil...,GR1,NaN
327,66587,NaN,Pato RodrÃ­guez,Pato RodrÃ­guez,2019,979,pato-rodriguez,Argentina,Quilmes,Argentina,...,right,172.0,500000.0,2400000.0,NaN,AAmanagers,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/pato-rodriguez...,PO1,NaN
489,125735,Luis,FariÃ±a,Luis FariÃ±a,2018,3336,luis-farina,Argentina,Buenos Aires,Argentina,...,right,177.0,150000.0,3000000.0,2023-12-31 00:00:00,The Kwan,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/luis-farina/pr...,PO1,NaN
532,148231,Lucas,Mugni,Lucas Mugni,2020,820,lucas-mugni,Argentina,Santa Fe,Argentina,...,left,184.0,300000.0,2500000.0,2023-12-31 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucas-mugni/pr...,TR1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27532,40822,Mauro,Boselli,Mauro Boselli,2012,458,mauro-boselli,Argentina,Buenos Aires,Argentina,...,right,185.0,250000.0,7500000.0,2023-12-31 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/mauro-boselli/...,IT1,NaN
27899,27448,Marcos,Angeleri,Marcos Angeleri,2015,1084,marcos-angeleri,Argentina,Treinta de Agosto,Argentina,...,right,183.0,NaN,3750000.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/marcos-angeler...,ES1,NaN
27995,324946,Emanuel,Cecchini,Emanuel Cecchini,2017,1084,emanuel-cecchini,Argentina,Ingeniero Huergo,Argentina,...,right,179.0,350000.0,4000000.0,2023-12-31 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/emanuel-cecchi...,ES1,NaN
28255,153022,NicolÃ¡s,Blandi,NicolÃ¡s Blandi,2014,14171,nicolas-blandi,Argentina,Campana,Argentina,...,right,180.0,250000.0,6000000.0,2023-12-31 00:00:00,Interplayers,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/nicolas-blandi...,FR1,NaN
28277,55884,Pablo,PÃ©rez,Pablo PÃ©rez,2013,1084,pablo-perez,Argentina,Rosario,Argentina,...,right,175.0,200000.0,2100000.0,2023-12-31 00:00:00,Carlos Bilicich,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/pablo-perez/pr...,ES1,NaN

In [9]:
players.current_club_name.unique()

array(['Krylya Sovetov Samara', 'SC Freiburg', 'SC Heerenveen', nan,
       'Ajax Amsterdam', 'Leicester City', 'St. Johnstone FC',
       'Heart of Midlothian FC', 'Rangers FC', 'Aston Villa',
       'Chelsea FC', 'Eintracht Frankfurt', 'RKC Waalwijk', 'RFC Seraing',
       'Galatasaray', 'Paris Saint-Germain', 'FC Nantes',
       'ACF Fiorentina', 'Getafe CF', 'Juventus FC', 'Elche CF',
       'APO Levadiakos', 'AtlÃ©tico de Madrid', 'KVC Westerlo',
       'OFI Crete FC', 'Cercle Brugge', 'Fenerbahce', 'Sivasspor',
       'Hibernian FC', 'Crystal Palace', 'Aberdeen FC', 'Panetolikos GFS',
       'KV Oostende', 'Royal Antwerp FC', 'Brighton & Hove Albion',
       'AFC Bournemouth', 'Gil Vicente FC', 'FC Augsburg', 'LOSC Lille',
       'Bayer 04 Leverkusen', 'Aarhus GF', 'Aris Thessaloniki',
       'KAA Gent', 'Olympique Marseille', 'Olympique Lyon',
       'Olympiacos Piraeus', 'FC PaÃ§os de Ferreira', 'AC Horsens',
       'AZ Alkmaar', 'US Sassuolo', 'FC Empoli', 'Spezia Calcio',
       'Club Brugge KV', 'PAOK Thessaloniki', 'FC Arouca', 'FK Rostov',
       'Real Betis BalompiÃ©', 'Akhmat Grozny', 'FC Porto', 'FC Toulouse',
       'US Salernitana 1919', 'Alanyaspor', 'RSC Charleroi', 'FC Lorient',
       '1.FSV Mainz 05', 'FC Copenhagen', 'GD Estoril Praia',
       'Inter Milan', 'CA Osasuna', 'St. Mirren FC', 'Real Valladolid CF',
       'Villarreal CF', 'AEK Athens', 'Besiktas JK', 'Motherwell FC',
       'AC Milan', 'GD Chaves', '1.FC KÃ¶ln', 'Standard LiÃ¨ge',
       'Boavista FC', 'Montpellier HSC', 'Real Madrid', 'Ãœmraniyespor',
       'Torpedo Moscow', 'PAS Giannina', 'VfB Stuttgart', 'Kilmarnock FC',
       'KV Kortrijk', 'RSC Anderlecht', 'Asteras Tripolis',
       'Athletic Bilbao', 'West Ham United', 'Rayo Vallecano',
       'Udinese Calcio', 'Ural Yekaterinburg', 'FK Krasnodar',
       'FK Khimki', 'RC Strasbourg Alsace', 'Sparta Rotterdam',
       'Chornomorets Odessa', 'Zorya Lugansk', 'FK Minaj',
       'Excelsior Rotterdam', 'Bologna FC 1909', 'Fatih KaragÃ¼mrÃ¼k',
       'Go Ahead Eagles', 'FK Orenburg', 'Manchester United',
       'UC Sampdoria', 'Fulham FC', 'Leeds United', 'Kayserispor',
       'MKE AnkaragÃ¼cÃ¼', 'Panathinaikos Athens', 'KAS Eupen',
       'VfL Wolfsburg', 'RB Leipzig', 'Atalanta BC', 'RC Lens',
       'Portimonense SC', 'CD Santa Clara', 'Brentford FC', 'Girona FC',
       '1.FC Union Berlin', 'Fortuna Sittard', 'VitÃ³ria GuimarÃ£es SC',
       'Valencia CF', 'Atromitos Athen', 'Randers FC', 'Dynamo Moscow',
       'Sporting CP', 'BrÃ¶ndby IF', 'Livingston FC', 'Vitesse Arnhem',
       'ESTAC Troyes', 'Rio Ave FC', 'CS MarÃ­timo', 'Hellas Verona',
       'SS Lazio', 'SL Benfica', 'Basaksehir FK', 'Aalborg BK',
       'Dynamo Kyiv', 'Dundee United FC', 'FC Pari Nizhniy Novgorod',
       'Clermont Foot 63', 'Zenit St. Petersburg', 'RCD Mallorca',
       'Hertha BSC', 'VfL Bochum', 'AS Monaco', 'KV Mechelen',
       'Stade Brestois 29', 'AS Roma', 'Sint-Truidense VV',
       'Stade Rennais FC', 'Nottingham Forest', 'Metalist 1925 Kharkiv',
       'Spartak Moscow', 'FC Midtjylland', 'FC Groningen',
       'Celta de Vigo', 'Ingulets Petrove', 'Kasimpasa', 'PAS Lamia 1964',
       'Silkeborg IF', 'Manchester City', 'Torino FC', 'SK Dnipro-1',
       'SC Cambuur Leeuwarden', 'Angers SCO', 'Casa Pia AC',
       'FC Volendam', 'Metalist Kharkiv', 'Stade Reims', 'Giresunspor',
       'Feyenoord Rotterdam', 'Bayern Munich', 'OGC Nice', 'AC Monza',
       'Viborg FF', 'RCD Espanyol Barcelona', 'Fakel Voronezh',
       'Adana Demirspor', 'Trabzonspor', 'Kolos Kovalivka',
       'Shakhtar Donetsk', 'Lokomotiv Moscow', 'Wolverhampton Wanderers',
       'Everton FC', 'Rukh Lviv', 'Kryvbas Kryvyi Rig',
       'TSG 1899 Hoffenheim', 'Real Sociedad', 'SC Braga', 'Istanbulspor',
       'AJ Auxerre', 'CÃ¡diz CF', 'FC Schalke 04', 'Liverpool FC',
       'UD AlmerÃ­a', 'Antalyaspor', 'Oud-Heverlee Leuven',
       'Tottenham Hotspur', 'KRC Genk', 'Newcastle United',
       'US Cremonese', 'CSKA Moscow', 'Borussia MÃ¶nchengladbach',
       'Southampton FC', 'Volos NPS', 'FC Nordsjaelland',
       'SV Zulte Waregem', 'FC Emmen', 'AC Ajaccio', 'Lyngby BK',
       'Hatayspor', 'FC Sochi', 'SV Werder Bremen', 'US Lecce',
       'Gaziantep FK', 'FC Utrecht', 'Sevilla FC', 'Ionikos Nikeas',
       'FC FamalicÃ£o', 'Arsenal FC', 'Borussia Dortmund', 'SSC Napoli',
       'Ross County FC', 'Twente Enschede FC', 'FC Vizela', 'Celtic FC',
       'PSV Eindhoven', 'NEC Nijmegen', 'Royale Union Saint Gilloise',
       'FC Barcelona', 'Konyaspor'], dtype=object)